Import('env')

env.MonitorPrinter('include/monitor_utils_h.v','#rtl/include/copperv_h.v')
env.Program('copperv_tools.vpi','copperv_tools.c')

sim_src = Glob('*.v')+Glob('*.sv')
sim_src = [f for f in sim_src if f.name != 'checker_cpu.v']
rtl_src = Glob('#rtl/*.v')

vvp = env.IVerilog('sim.vvp',sim_src + rtl_src)

vcd_file = 'sim.vcd'
env.Append(PLUSARGS = {'VCD_FILE':vcd_file})
vcd = env.VVP(vcd_file,vvp)

env.Depends(vcd, env['HEX_FILE'])
env.Depends(vcd, env['DISS_FILE'])

