
dhrystone.hex: dhrystone.elf
dhrystone.elf: dhrystone_main.o dhrystone.o

#CFLAGS+=-DToo_Small_Time=0 -DNUMBER_OF_RUNS=1 -DDEBUG_RUN
#CFLAGS+=-DDEBUG_RUN
#CFLAGS+=-DDEBUG_RUNTIME

include ../common/Makefile
