.PHONY: all
all: run

include Makefile.common

.PHONY: clean
clean:
	rm -rfv obj_dir *.vcd *.log

obj_dir/sim:
	verilator -Wall -Wno-fatal --threads $(shell nproc) $(COMPILE_ARGS) -o $(notdir $@) --trace-fst --top-module $(TOPLEVEL) --cc --exe --build sim_main.cpp $(VERILOG_SOURCES) 

.PHONY: run
run: obj_dir/sim $(HEX_FILE)
	date
	./obj_dir/sim $(PLUSARGS)
	date
	@echo
	@echo fake_uart:
	@cat obj_dir/fake_uart.log

