// Auto generated by ../scripts/magic_numbers.py 2020-05-03 17:13:26.896369

function `STRING state;
input [`STATE_WIDTH-1:0] arg;
begin
    case (arg)
        `STATE_RESET:
            state = "RESET";
        `STATE_IDLE:
            state = "IDLE";
        `STATE_FETCH:
            state = "FETCH";
        `STATE_LOAD:
            state = "LOAD";
        `STATE_EXEC:
            state = "EXEC";
        `STATE_MEM:
            state = "MEM";
        default:
            state = "UNKNOWN";
    endcase
end
endfunction

function `STRING inst_type;
input [`INST_TYPE_WIDTH-1:0] arg;
begin
    case (arg)
        `INST_TYPE_IMM:
            inst_type = "IMM";
        `INST_TYPE_INT_IMM:
            inst_type = "INT_IMM";
        `INST_TYPE_INT_REG:
            inst_type = "INT_REG";
        `INST_TYPE_BRANCH:
            inst_type = "BRANCH";
        default:
            inst_type = "UNKNOWN";
    endcase
end
endfunction
