// Auto generated by ../scripts/magic_numbers.py 2020-05-11 00:45:21.633315

function `STRING state;
input [`STATE_WIDTH-1:0] arg;
begin
    case (arg)
        `STATE_RESET:
            state = "RESET";
        `STATE_IDLE:
            state = "IDLE";
        `STATE_FETCH:
            state = "FETCH";
        `STATE_LOAD:
            state = "LOAD";
        `STATE_EXEC:
            state = "EXEC";
        `STATE_MEM:
            state = "MEM";
        default:
            state = "UNKNOWN";
    endcase
end
endfunction

function `STRING inst_type;
input [`INST_TYPE_WIDTH-1:0] arg;
begin
    case (arg)
        `INST_TYPE_IMM:
            inst_type = "IMM";
        `INST_TYPE_INT_IMM:
            inst_type = "INT_IMM";
        `INST_TYPE_INT_REG:
            inst_type = "INT_REG";
        `INST_TYPE_BRANCH:
            inst_type = "BRANCH";
        default:
            inst_type = "UNKNOWN";
    endcase
end
endfunction

function `STRING funct;
input [`FUNCT_WIDTH-1:0] arg;
begin
    case (arg)
        `FUNCT_ADD:
            funct = "ADD";
        `FUNCT_SUB:
            funct = "SUB";
        `FUNCT_EQ:
            funct = "EQ";
        `FUNCT_NEQ:
            funct = "NEQ";
        default:
            funct = "UNKNOWN";
    endcase
end
endfunction

function `STRING pc_next_sel;
input [`PC_NEXT_SEL_WIDTH-1:0] arg;
begin
    case (arg)
        `PC_NEXT_SEL_STALL:
            pc_next_sel = "STALL";
        `PC_NEXT_SEL_INCR:
            pc_next_sel = "INCR";
        `PC_NEXT_SEL_BRANCH:
            pc_next_sel = "BRANCH";
        default:
            pc_next_sel = "UNKNOWN";
    endcase
end
endfunction
